<?php require 'layout/header.phtml' ?>
<?php //require '/layout/footer.phtml' ?>


<h1>Films</h1>
<ul>
    <?php foreach($films as $film): ?>

        <li>
            <a href="films/<?= $film -> id ?>">
                <?=  $film -> nombre ?>
            </a>


    <?php endforeach ?>
    <?php
//    $password = 'admin'; // The plain text password
//    $hashedPassword = password_hash($password, PASSWORD_BCRYPT);
//
//    echo $hashedPassword;
    ?>
</ul>