<?php require_once 'layout/header.phtml'; ?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Director</title>
</head>
<body>

    <h1>Agregar Director</h1>

    <form action="agregarDirector" method="POST">
        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" id="nombre" required><br><br>

        <input type="submit" value="Agregar Director">
    </form>

</body>
</html>